export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const FAILED_REQUEST_POSTS = 'FAILED_REQUEST_POSTS'

export const REQUEST_COMMENTS = 'REQUEST_COMMENTS'
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'
export const FAILED_REQUEST_COMMENTS = 'FAILED_REQUEST_COMMENTS'
