export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const FAILED_REQUEST_POSTS = 'FAILED_REQUEST_POSTS'

export const REQUEST_COMMENTS = 'REQUEST_COMMENTS'
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'
export const FAILED_REQUEST_COMMENTS = 'FAILED_REQUEST_COMMENTS'

export const REQUEST_USER = 'REQUEST_USER'
export const RECEIVE_USER = 'RECEIVE_USER'
export const FAILED_REQUEST_USER = 'FAILED_REQUEST_USER'

export const SET_TITLE = 'SET_TITLE'

export const REQUEST_FRONT_PAGE = 'REQUEST_FRONT_PAGE'
